site_name: Life Sciences

site_url: https://AristaLifeSciences.github.io/Newsletter/
repo_name: AristaLifeSciences/Newsletter
docs_dir: docs/
edit_uri: https://github.com/AristaLifeSciences/Newsletter/edit/master/docs/

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all

theme:
  name: material
  icon:
    admonition:
      quote: octicons/quote-16
      note: octicons/tag-16
  palette:
    primary: custom
  logo: 
  favicon: img/arista_logo.png

nav:
  - www.arista.com: http://www.arista.com
  - September 2025: index.md


extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright Â© 2025 Arista Networks. You are receiving this newsletter as a customer of Arista. 

