site_name: Life Sciences Newsletter

site_url: https://aristalifesciences.github.io/Life-Sciences-Newsletter/
repo_name: AristaLifeSciences/Newsletter
docs_dir: docs/
edit_uri: https://github.com/AristaLifeSciences/Newsletter/edit/master/docs/

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all


theme:
  name: material
  icon:
    admonition:
      quote: octicons/quote-16
      note: octicons/tag-16
  palette:
    primary: custom
  logo: img/logo_arista.png
  favicon: img/arista_favicon.ico
   
nav:
  - www.arista.com: http://www.arista.com
  - November 2025: index.md
  - Resources:
    - AI Networking Whitepaper: https://www.arista.com/assets/data/pdf/Whitepapers/AI-Network-WP.pdf
    - New Era of AI Centers: https://blogs.arista.com/blog/ai-center
    - Gen AI and Agentic AI Revolution: https://blogs.arista.com/blog/generative-and-agentic-ai-networking-revolution
    - Scale Up Ethernet: https://blogs.arista.com/blog/the-sun-rises-on-scale-up-ethernet


extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright Â© 2025 Arista Networks. You are receiving this newsletter as a customer of Arista. 

